#KubeJS Common Properties
#Wed Mar 12 02:20:23 CDT 2025
matchJsonRecipes=true
allowAsyncStreams=false
announceReload=true
startupErrorGUI=true
serverOnly=false
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=minecraft\:purple_dye
startupErrorReportUrl=
