#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Apr 17 19:25:50 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Chocapic13_V9_Low.zip
enableShaders=false
